import '../models/user.dart';        // [IMPORT] User data model class
import '../models/follow.dart';      // [IMPORT] Follow relationship data model class
import '../models/comment.dart';    // [IMPORT] Comment data model class
import 'mock_data_service.dart';    // [IMPORT] Local mock data storage service

/// [CLASS] SocialService
/// [PURPOSE] Manages social features: follow/unfollow, likes, comments
/// [USES] MockDataService for local in-memory data storage
class SocialService {
  
  // [FIELD] _mockService - Singleton instance of MockDataService
  final MockDataService _mockService = MockDataService();

  /// [FUNCTION] followUser
  /// [PARAMS] followerId - UID of user who wants to follow
  /// [PARAMS] followingId - UID of user to be followed
  /// [RETURNS] Future<void>
  /// [PURPOSE] Creates a follow relationship between two users
  Future<void> followUser(String followerId, String followingId) async {
    try {
      await _mockService.followUser(followerId, followingId);
    } catch (e) {
      throw Exception('Failed to follow user: $e');
    }
  }

  /// [FUNCTION] unfollowUser
  /// [PARAMS] followerId - UID of user who wants to unfollow
  /// [PARAMS] followingId - UID of user to be unfollowed
  /// [RETURNS] Future<void>
  /// [PURPOSE] Removes a follow relationship between two users
  Future<void> unfollowUser(String followerId, String followingId) async {
    try {
      await _mockService.unfollowUser(followerId, followingId);
    } catch (e) {
      throw Exception('Failed to unfollow user: $e');
    }
  }

  /// [FUNCTION] isFollowing
  /// [PARAMS] followerId - UID of potential follower
  /// [PARAMS] followingId - UID of potential followed user
  /// [RETURNS] Future<bool> - true if following, false if not
  /// [PURPOSE] Checks if followerId follows followingId
  Future<bool> isFollowing(String followerId, String followingId) async {
    try {
      return await _mockService.isFollowing(followerId, followingId);
    } catch (e) {
      throw Exception('Failed to check follow status: $e');
    }
  }

  /// [FUNCTION] getFollowers
  /// [PARAMS] userId - UID of user whose followers to retrieve
  /// [RETURNS] Future<List<UserModel>> - list of followers (currently empty for mock)
  /// [PURPOSE] Retrieves all followers of a specific user
  Future<List<UserModel>> getFollowers(String userId) async {
    // [NOTE] MockDataService returns int count in its simple form.
    // [NOTE] For local-only, we'll return an empty list or implement if needed.
    return [];
  }

  /// [FUNCTION] getFollowing
  /// [PARAMS] userId - UID of user whose following list to retrieve
  /// [RETURNS] Future<List<UserModel>> - list of users being followed (currently empty for mock)
  /// [PURPOSE] Retrieves all users that userId follows
  Future<List<UserModel>> getFollowing(String userId) async {
    return [];
  }

  /// [FUNCTION] addComment
  /// [PARAMS] postId - ID of post being commented on
  /// [PARAMS] userId - UID of comment author
  /// [PARAMS] username - Display name of comment author
  /// [PARAMS] content - Comment text content
  /// [PARAMS] userProfileImage - Optional URL to commenter's profile image
  /// [RETURNS] Future<void>
  /// [PURPOSE] Creates and saves a new comment on a post
  Future<void> addComment({
    required String postId,
    required String userId,
    required String username,
    required String content,
    String? userProfileImage,
  }) async {
    try {
      // [STEP 1] Create CommentModel instance with current timestamp
      final comment = CommentModel(
        id: '',                        // [FIELD] ID will be generated by MockDataService
        postId: postId,                // [FIELD] Link to parent post
        userId: userId,                // [FIELD] Comment author UID
        username: username,            // [FIELD] Comment author display name
        userProfileImage: userProfileImage,  // [FIELD] Optional profile image URL
        content: content,              // [FIELD] Comment text content
        createdAt: DateTime.now(),     // [FIELD] Creation timestamp
      );
      // [STEP 2] Save comment to mock data service
      await _mockService.addComment(comment);
    } catch (e) {
      throw Exception('Failed to add comment: $e');
    }
  }

  /// [FUNCTION] deleteComment
  /// [PARAMS] commentId - ID of comment to delete
  /// [PARAMS] postId - ID of post containing the comment (for validation)
  /// [RETURNS] Future<void>
  /// [PURPOSE] Removes a comment from a post
  Future<void> deleteComment(String commentId, String postId) async {
    try {
      await _mockService.deleteComment(commentId);
    } catch (e) {
      throw Exception('Failed to delete comment: $e');
    }
  }

  /// [FUNCTION] getComments
  /// [PARAMS] postId - ID of post whose comments to retrieve
  /// [RETURNS] Future<List<CommentModel>> - list of comments on the post
  /// [PURPOSE] Retrieves all comments for a specific post
  Future<List<CommentModel>> getComments(String postId) async {
    try {
      return await _mockService.getPostComments(postId);
    } catch (e) {
      throw Exception('Failed to get comments: $e');
    }
  }

  /// [FUNCTION] likePost
  /// [PARAMS] postId - ID of post to like
  /// [PARAMS] userId - UID of user who likes the post
  /// [RETURNS] Future<void>
  /// [PURPOSE] Creates a like relationship between user and post
  Future<void> likePost(String postId, String userId) async {
    try {
      await _mockService.likePost(postId, userId);
    } catch (e) {
      throw Exception('Failed to like post: $e');
    }
  }

  /// [FUNCTION] unlikePost
  /// [PARAMS] postId - ID of post to unlike
  /// [PARAMS] userId - UID of user who unlikes the post
  /// [RETURNS] Future<void>
  /// [PURPOSE] Removes a like relationship between user and post
  Future<void> unlikePost(String postId, String userId) async {
    try {
      await _mockService.unlikePost(postId, userId);
    } catch (e) {
      throw Exception('Failed to unlike post: $e');
    }
  }

  /// [FUNCTION] isPostLiked
  /// [PARAMS] postId - ID of post to check
  /// [PARAMS] userId - UID of user to check
  /// [RETURNS] Future<bool> - true if liked, false if not
  /// [PURPOSE] Checks if userId has liked postId
  Future<bool> isPostLiked(String postId, String userId) async {
    try {
      return await _mockService.isPostLiked(postId, userId);
    } catch (e) {
      throw Exception('Failed to check like status: $e');
    }
  }
}
