// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuNxE7iYclOQnjXFcSnULp0MIWV1iD4Ks',
    appId: '1:995314110713:web:06df8f5dd8471a6d7b9228',
    messagingSenderId: '995314110713',
    projectId: 'midtermsocialmemories-63575',
    authDomain: 'midtermsocialmemories-63575.firebaseapp.com',
    storageBucket: 'midtermsocialmemories-63575.firebasestorage.app',
    measurementId: 'G-RN525ZN243',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNrj72ozT-FdGfg1txkz3GVJ_6TI6s5a4',
    appId: '1:995314110713:android:1c1f49b070124d7b7b9228',
    messagingSenderId: '995314110713',
    projectId: 'midtermsocialmemories-63575',
    storageBucket: 'midtermsocialmemories-63575.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxl9ydESOIIHkRjlapJvcdQkuVY1pDCbA',
    appId: '1:626837611317:ios:44328bed714cc06f98e27c',
    messagingSenderId: '626837611317',
    projectId: 'android-app-23523',
    storageBucket: 'android-app-23523.firebasestorage.app',
    iosBundleId: 'com.example.socialMemoriesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxl9ydESOIIHkRjlapJvcdQkuVY1pDCbA',
    appId: '1:626837611317:ios:44328bed714cc06f98e27c',
    messagingSenderId: '626837611317',
    projectId: 'android-app-23523',
    storageBucket: 'android-app-23523.firebasestorage.app',
    iosBundleId: 'com.example.socialMemoriesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPdlAlvywNedttfw5kDFGn9NgpQfMrP2w',
    appId: '1:626837611317:web:816ac2ab93c8ada998e27c',
    messagingSenderId: '626837611317',
    projectId: 'android-app-23523',
    authDomain: 'android-app-23523.firebaseapp.com',
    storageBucket: 'android-app-23523.firebasestorage.app',
  );

}